//! Team export decryption, verification, and serialization.
//!
//! Handles cryptographic envelopes generated by the web squad builder (`https://ievr-ultimate-team.fly.dev/`).
//! Recovered passphrase: `Rmfr4Dic6EAQaSgmLF__S64v7AgTNXb3q7-BLsBO5_0`.

use std::num::NonZeroU32;

use aes_gcm::aead::{Aead, KeyInit};
use aes_gcm::{Aes256Gcm, Nonce};
use base64::engine::general_purpose::STANDARD as BASE64;
use base64::Engine;
use pbkdf2::pbkdf2_hmac;
use serde::{Deserialize, Serialize};
use sha2::Sha256;

use crate::error::{LauncherError, Result};

/// Canonical hardcoded passphrase recovered from `exportarPlantilla-D5SK__eT.js`.
pub const DEFAULT_PASSPHRASE: &str = "Rmfr4Dic6EAQaSgmLF__S64v7AgTNXb3q7-BLsBO5_0";

/// Number of PBKDF2 iterations configured on the web client.
pub const DEFAULT_ITERATIONS: u32 = 210_000;

/// Encrypted envelope structure saved by the web application.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TeamExportEnvelope {
    pub v: u32,
    pub alg: String,
    pub salt: String,
    pub iv: String,
    pub datos: String,
}

/// A single character assignment in an exported squad.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TeamCharacter {
    pub slot: u32,
    pub param_id_crc: u32,
    #[serde(rename = "charaRarity")]
    pub chara_rarity: u32,
    pub skill_count: u32,
}

/// Decrypted team lineup specification.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TeamLineup {
    #[serde(rename = "formationId", skip_serializing_if = "Option::is_none")]
    pub formation_id: Option<u32>,
    #[serde(rename = "emblemId", skip_serializing_if = "Option::is_none")]
    pub emblem_id: Option<u32>,
    #[serde(rename = "teamName")]
    pub team_name: String,
    #[serde(rename = "tacticsId")]
    pub tactics_id: Vec<u32>,
    #[serde(rename = "uniformId", skip_serializing_if = "Option::is_none")]
    pub uniform_id: Option<u32>,
    pub characters: Vec<TeamCharacter>,
}

/// Decrypt an exported team envelope JSON string or struct using the recovered key.
pub fn decrypt_team_envelope(envelope: &TeamExportEnvelope, passphrase: &str) -> Result<TeamLineup> {
    let salt = BASE64.decode(&envelope.salt)?;
    let iv = BASE64.decode(&envelope.iv)?;
    let ciphertext = BASE64.decode(&envelope.datos)?;

    if iv.len() != 12 {
        return Err(LauncherError::Crypto(format!(
            "invalid IV length: expected 12 bytes, got {}",
            iv.len()
        )));
    }

    let mut derived_key = [0u8; 32];
    let rounds = NonZeroU32::new(DEFAULT_ITERATIONS).unwrap();
    pbkdf2_hmac::<Sha256>(passphrase.as_bytes(), &salt, rounds.get(), &mut derived_key);

    let cipher = Aes256Gcm::new_from_slice(&derived_key)
        .map_err(|e| LauncherError::Crypto(format!("failed to initialize AES-256-GCM: {e}")))?;

    let nonce = Nonce::from_slice(&iv);
    let plaintext = cipher
        .decrypt(nonce, ciphertext.as_ref())
        .map_err(|e| LauncherError::Crypto(format!("AES-GCM decryption failed: {e}")))?;

    let lineup: TeamLineup = serde_json::from_slice(&plaintext)?;
    Ok(lineup)
}

/// Encrypt a team lineup into an envelope for interoperability with UTLauncher.
pub fn encrypt_team_envelope(
    lineup: &TeamLineup,
    passphrase: &str,
    salt: &[u8; 16],
    iv: &[u8; 12],
) -> Result<TeamExportEnvelope> {
    let mut derived_key = [0u8; 32];
    let rounds = NonZeroU32::new(DEFAULT_ITERATIONS).unwrap();
    pbkdf2_hmac::<Sha256>(passphrase.as_bytes(), salt, rounds.get(), &mut derived_key);

    let cipher = Aes256Gcm::new_from_slice(&derived_key)
        .map_err(|e| LauncherError::Crypto(format!("failed to initialize AES-256-GCM: {e}")))?;

    let plaintext = serde_json::to_vec_pretty(lineup)?;
    let nonce = Nonce::from_slice(iv);

    let ciphertext = cipher
        .encrypt(nonce, plaintext.as_ref())
        .map_err(|e| LauncherError::Crypto(format!("AES-GCM encryption failed: {e}")))?;

    Ok(TeamExportEnvelope {
        v: 1,
        alg: "AES-256-GCM+PBKDF2-SHA256".to_string(),
        salt: BASE64.encode(salt),
        iv: BASE64.encode(iv),
        datos: BASE64.encode(ciphertext),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_team_roundtrip_cryptography() {
        let original = TeamLineup {
            formation_id: Some(3),
            emblem_id: Some(105),
            team_name: "Inazuma Japan".to_string(),
            tactics_id: vec![10, 20, 30],
            uniform_id: Some(7),
            characters: vec![
                TeamCharacter {
                    slot: 0,
                    param_id_crc: 0x12345678,
                    chara_rarity: 5,
                    skill_count: 6,
                },
                TeamCharacter {
                    slot: 1,
                    param_id_crc: 0x9ABCDEF0,
                    chara_rarity: 8,
                    skill_count: 9,
                },
            ],
        };

        let salt = [0x42u8; 16];
        let iv = [0x24u8; 12];

        let envelope = encrypt_team_envelope(&original, DEFAULT_PASSPHRASE, &salt, &iv).unwrap();
        let decrypted = decrypt_team_envelope(&envelope, DEFAULT_PASSPHRASE).unwrap();

        assert_eq!(original, decrypted);
    }
}
