/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_modelviewer_free: (a: number, b: number) => void;
export const modelviewer_backend_info: (a: number, b: number) => void;
export const modelviewer_clear_assets: (a: number) => void;
export const modelviewer_create: (a: number) => number;
export const modelviewer_create_transparent: (a: number) => number;
export const modelviewer_gizmo_axis_at: (a: number, b: number, c: number, d: number) => void;
export const modelviewer_gizmo_drag: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const modelviewer_gizmo_rotate: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const modelviewer_gizmo_scale: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const modelviewer_load_glb: (a: number, b: number, c: number, d: number) => void;
export const modelviewer_load_scene: (a: number, b: number, c: number, d: number) => void;
export const modelviewer_orbit: (a: number, b: number, c: number, d: number, e: number) => void;
export const modelviewer_pick_json: (a: number, b: number, c: number, d: number) => void;
export const modelviewer_render: (a: number, b: number) => void;
export const modelviewer_resize: (a: number, b: number, c: number, d: number) => void;
export const modelviewer_scene_stats_json: (a: number, b: number) => void;
export const modelviewer_select: (a: number, b: number, c: number) => void;
export const modelviewer_selected: (a: number, b: number) => void;
export const modelviewer_set_gizmo_mode: (a: number, b: number, c: number) => void;
export const modelviewer_set_grid: (a: number, b: number) => void;
export const modelviewer_set_wireframe: (a: number, b: number) => void;
export const modelviewer_stage_asset: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const start: () => void;
export const __wasm_bindgen_func_elem_7089: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_7110: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_1532: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_1532_2: (a: number, b: number, c: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_export5: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
