import {
	AlertCircle,
	Archive,
	ArrowLeft,
	ArrowLeftRight,
	ArrowRight,
	ArrowUpDown,
	ArrowUpLeft,
	AtSign,
	AudioLines,
	Backpack,
	BadgeCheck,
	Ban,
	BarChart3,
	BookOpen,
	Box,
	Boxes,
	Braces,
	Calculator,
	Calendar,
	Captions,
	Check,
	CheckCircle2,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Circle,
	CircleDot,
	CircleUser,
	Clock,
	Coins,
	Compass,
	Copy,
	Cpu,
	Database,
	Dices,
	Download,
	Dumbbell,
	Eraser,
	ExternalLink,
	Eye,
	EyeOff,
	FileText,
	Film,
	FilterX,
	Flame,
	Folder,
	FolderOpen,
	FolderTree,
	Frown,
	Gauge,
	Gift,
	Heart,
	History,
	Home,
	Hourglass,
	Image,
	ImageOff,
	Images,
	Info,
	Languages,
	LayoutDashboard,
	LayoutGrid,
	Lightbulb,
	LineChart,
	List,
	ListChecks,
	ListFilter,
	Lock,
	LockOpen,
	LogIn,
	Map,
	MapPin,
	Maximize,
	Medal,
	Menu,
	MessageSquare,
	Minimize,
	Moon,
	Music,
	Network,
	Newspaper,
	Package,
	PartyPopper,
	Pause,
	PawPrint,
	Pencil,
	Pin,
	Play,
	PlayCircle,
	Plus,
	Pointer,
	Puzzle,
	RefreshCw,
	Repeat,
	RotateCcw,
	Rows3,
	Rss,
	Save,
	ScanSearch,
	Search,
	SearchX,
	Settings,
	Share2,
	Shield,
	ShieldCheck,
	ShoppingBag,
	SkipBack,
	SkipForward,
	SlidersHorizontal,
	Sparkles,
	Star,
	Store,
	Sun,
	Sunrise,
	Swords,
	Table,
	Tag,
	Timer,
	Trash2,
	TreePine,
	TrendingUp,
	TriangleAlert,
	Trophy,
	Undo2,
	Upload,
	User,
	UserMinus,
	UserPlus,
	Users,
	VideoOff,
	Volume2,
	VolumeX,
	WandSparkles,
	Wifi,
	Wind,
	Wrench,
	X,
	Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/**
 * Mapping centralisé des noms d'icônes Material Symbols vers les composants Lucide React.
 * Utilisé par <Icon name="..." /> et les composants navigation (config/navigation.ts stocke des strings).
 */
export const iconMap: Record<string, LucideIcon> = {
	account_circle: CircleUser,
	account_tree: FolderTree,
	add: Plus,
	air: Wind,
	alternate_email: AtSign,
	analytics: LineChart,
	archive: Archive,
	arrow_back: ArrowLeft,
	arrow_forward: ArrowRight,
	article: FileText,
	auto_awesome: Sparkles,
	auto_fix_high: Sparkles,
	auto_stories: BookOpen,
	backpack: Backpack,
	bar_chart: BarChart3,
	block: Ban,
	blur_on: CircleDot,
	bolt: Zap,
	broken_image: ImageOff,
	build: Wrench,
	calculate: Calculator,
	calendar_today: Calendar,
	casino: Dices,
	category: LayoutGrid,
	change_circle: RefreshCw,
	check: Check,
	check_circle: CheckCircle2,
	chevron_left: ChevronLeft,
	chevron_right: ChevronRight,
	close: X,
	compare_arrows: ArrowLeftRight,
	content_copy: Copy,
	cyclone: Wind,
	dark_mode: Moon,
	dashboard: LayoutDashboard,
	data_object: Braces,
	database: Database,
	deployed_code: Boxes,
	delete: Trash2,
	delete_sweep: Eraser,
	description: FileText,
	download: Download,
	edit: Pencil,
	edit_note: FileText,
	electric_bolt: Zap,
	emoji_events: Trophy,
	error: AlertCircle,
	expand_less: ChevronUp,
	expand_more: ChevronDown,
	extension: Puzzle,
	favorite: Heart,
	feed: Rss,
	female: User,
	filter_alt_off: FilterX,
	filter_list: ListFilter,
	fitness_center: Dumbbell,
	flash_on: Zap,
	folder: Folder,
	folder_open: FolderOpen,
	forest: TreePine,
	forum: MessageSquare,
	fullscreen: Maximize,
	fullscreen_exit: Minimize,
	gavel: Shield,
	graphic_eq: AudioLines,
	grid_view: LayoutGrid,
	group: Users,
	group_add: UserPlus,
	groups: Users,
	history: History,
	home: Home,
	hourglass_top: Hourglass,
	image: Image,
	image_not_supported: ImageOff,
	image_search: ScanSearch,
	info: Info,
	insights: TrendingUp,
	inventory_2: Package,
	landscape: MountainIcon,
	light_mode: Sun,
	lightbulb: Lightbulb,
	link: ExternalLink,
	local_fire_department: Flame,
	lock: Lock,
	lock_open: LockOpen,
	login: LogIn,
	male: User,
	memory: Cpu,
	menu: Menu,
	menu_book: BookOpen,
	monitoring: TrendingUp,
	movie: Film,
	movie_off: VideoOff,
	music_note: Music,
	newspaper: Newspaper,
	north_west: ArrowUpLeft,
	open_in_new: ExternalLink,
	payments: Coins,
	perm_media: Images,
	person: User,
	person_celebrate: PartyPopper,
	person_remove: UserMinus,
	pets: PawPrint,
	pause: Pause,
	pin_drop: MapPin,
	play_arrow: Play,
	play_circle: PlayCircle,
	policy: ShieldCheck,
	publish: Upload,
	push_pin: Pin,
	radio_button_unchecked: Circle,
	redeem: Gift,
	replay: Repeat,
	rotate_ccw: RotateCcw,
	save: Save,
	schedule: Clock,
	schema: Network,
	search: Search,
	search_off: SearchX,
	sentiment_dissatisfied: Frown,
	settings: Settings,
	share: Share2,
	shield: Shield,
	shield_person: ShieldCheck,
	shopping_bag: ShoppingBag,
	skip_next: SkipForward,
	skip_previous: SkipBack,
	sort: ArrowUpDown,
	speed: Gauge,
	sports: Medal,
	sports_martial_arts: Swords,
	sports_mma: Swords,
	sports_soccer: CircleDot,
	stadium: CircleDot,
	stars: Star,
	store: Store,
	storefront: Store,
	strategy: Map,
	subtitles: Captions,
	swap_horiz: ArrowLeftRight,
	swords: Swords,
	table_chart: Table,
	table_rows: Rows3,
	tag: Tag,
	task_alt: ListChecks,
	// Collections de textures (`/textures`). Sans cette clé l'entrée de menu s'affiche
	// SANS icône, en silence : `iconMap[name]` vaut `undefined` et le rendu retombe sur `null`.
	texture: LayoutGrid,
	timer: Timer,
	touch_app: Pointer,
	translate: Languages,
	travel_explore: Compass,
	trending_up: TrendingUp,
	tune: SlidersHorizontal,
	undo: Undo2,
	update: RefreshCw,
	verified: BadgeCheck,
	verified_user: ShieldCheck,
	view_in_ar: Box,
	view_list: List,
	visibility: Eye,
	visibility_off: EyeOff,
	volume_off: VolumeX,
	volume_up: Volume2,
	wand: WandSparkles,
	warning: TriangleAlert,
	wb_twilight: Sunrise,
	whatshot: Flame,
	wifi_tethering: Wifi,
};

/** Noms d'icônes valides. Typer la clé transforme une faute de frappe en
 * erreur `tsc` au lieu d'une icône silencieusement absente à l'écran. */
export type IconName = keyof typeof iconMap;

// Re-export pour usage direct
export type { LucideIcon };
