"use client";

import { ArrowRightLeft, Backpack, Coins, Layers, MapPin, ShoppingBag, Star, Store } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Icon } from "../../ui/Icon";

const RARITY_LABELS: Record<string, string> = { "1": "Normal", "2": "Expérimenté", "3": "Normal", "4": "Normal", "5": "Normal" };
const CATEGORY_LABELS: Record<string, { label: string; icon: string }> = {
	accessory: { icon: "diamond", label: "Accessoire" }, animal: { icon: "pets", label: "Animal" }, consume: { icon: "local_pharmacy", label: "Consommable" }, costume: { icon: "apparel", label: "Costume" }, craft_obj: { icon: "construction", label: "Matériau" }, emblem: { icon: "shield", label: "Emblème" }, fashion: { icon: "styler", label: "Mode" }, formation: { icon: "sports", label: "Formation" }, important: { icon: "priority_high", label: "Objet clé" }, kizuna_link: { icon: "link", label: "Lien Kizuna" }, misanga: { icon: "wrist_band", label: "Bracelet" }, name_plate: { icon: "id_card", label: "Plaque" }, performance: { icon: "music_note", label: "Performance" }, shoes: { icon: "steps", label: "Chaussures" }, special: { icon: "star", label: "Spécial" }, special_skill: { icon: "auto_awesome", label: "Compétence sp." }, title: { icon: "badge", label: "Titre" },
};
const STAT_LABELS: Record<string, { label: string; icon: string }> = {
	agility: { icon: "directions_run", label: "Agilité" }, control: { icon: "touch_app", label: "Contrôle" }, intelligence: { icon: "psychology", label: "Intelligence" }, kick: { icon: "sports_soccer", label: "Tir" }, physical: { icon: "fitness_center", label: "Physique" }, pressure: { icon: "compress", label: "Pression" }, technique: { icon: "precision_manufacturing", label: "Technique" },
};
const LOCATION_FR: Record<string, string> = { Chronicle: "Galerie Chronique", "G-Mart (Arcade Branch)": "G-Mart (Succursale Arcade)", "G-Mart (Odaiba)": "G-Mart (Odaiba)", "Kool Kit (Odaiba Branch)": "Kool Kit (Succursale Odaiba)", "Special Training Booth": "Stand d'entraînement spécial", Spirit: "Marché des Esprits", VS: "Boutique VS" };

export interface ItemDetailImage { src: string; alt: string; className: string; onError: () => void; }
export interface ItemDetailRecipe { shop: string; costs: Array<{ name: string; code?: string; quantity: number }>; }
/** Data-only input for the shared item presentation. Hosts own VFS/CDN lookup and image rendering. */
export interface ItemDetailProps {
	itemName: string; itemDescription: string; imageSource?: string | null; renderImage?: (image: ItemDetailImage) => ReactNode; category: string; rarity?: string | number | null; price?: number | null; maxStack?: number | null; alternateNames?: { en?: string; ja?: string }; japaneseDescription?: string; japaneseRomanization?: string; bonuses?: Record<string, number> | null; communityLocation?: string; communityStats?: Record<string, number>; shops?: string[]; exchangeRecipes?: ItemDetailRecipe[] | null;
}

function StatRows({ entries, max, signed }: { entries: Array<[string, number]>; max: number; signed: boolean }) {
	return <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{entries.map(([key, value]) => {
		const info = STAT_LABELS[key] || { icon: "bar_chart", label: key }; const positive = value > 0; const pct = max > 0 ? Math.min(100, (Math.abs(value) / max) * 100) : 0;
		return <div key={key} className="flex items-center gap-3 px-3 py-2 rounded-xl bg-surface-container-high border border-outline-variant/10"><Icon name={info.icon} size={18} className="text-primary shrink-0" /><div className="flex-1 min-w-0"><div className="flex items-center justify-between mb-1"><span className="text-[10px] font-bold text-on-surface-variant uppercase opacity-60">{info.label}</span><span className={`text-sm font-black ${signed ? (positive ? "text-primary" : "text-error") : "text-on-surface"}`}>{signed && positive ? "+" : ""}{value}</span></div><div className="h-1.5 rounded-full bg-outline-variant/20 overflow-hidden"><div className={`h-full rounded-full transition-all ${signed ? (positive ? "bg-primary" : "bg-error") : "bg-primary"}`} style={{ width: `${pct}%` }} /></div></div></div>;
	})}</div>;
}

/** Shared item sheet; hosts retain data loading, localized asset resolution and image implementation. */
export function ItemDetail({ itemName, itemDescription, imageSource, renderImage, category, rarity, price, maxStack, alternateNames, japaneseDescription, japaneseRomanization, bonuses, communityLocation, communityStats, shops, exchangeRecipes }: ItemDetailProps) {
	const [imageFailed, setImageFailed] = useState(false);
	const categoryInfo = CATEGORY_LABELS[category] || { icon: "backpack", label: category };
	const rarityLabel = rarity == null ? null : RARITY_LABELS[String(rarity)] || String(rarity);
	const bonusEntries = Object.entries(bonuses || {}).filter(([, value]) => Number.isFinite(value) && value !== 0);
	const communityEntries = Object.entries(communityStats || {}).filter(([key, value]) => key in STAT_LABELS && value > 0);
	const translatedLocation = communityLocation ? LOCATION_FR[communityLocation] || communityLocation : null;
	const hasDescription = Boolean(itemDescription && itemDescription !== "Aucune description.");
	const hasImage = Boolean(imageSource && renderImage && !imageFailed);
	return <div className="w-full space-y-8 animate-in fade-in zoom-in-95 duration-300">
		<div className="grid grid-cols-1 lg:grid-cols-[280px_1fr] gap-6 lg:gap-8 p-4 sm:p-6 lg:p-8 rounded-2xl sm:rounded-[32px] bg-surface-container border border-outline-variant/30 shadow-sm relative overflow-hidden"><div className="absolute top-0 right-0 size-96 bg-primary/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 pointer-events-none" />
			<div className="flex flex-col items-center gap-6"><div className="w-full aspect-square max-w-[200px] sm:max-w-[280px] rounded-2xl sm:rounded-3xl bg-surface-container-high flex items-center justify-center shrink-0 shadow-inner overflow-hidden relative border border-outline-variant/20">{hasImage ? renderImage!({ src: imageSource!, alt: itemName, className: "object-contain p-6 filter drop-shadow-lg", onError: () => setImageFailed(true) }) : <><Backpack size={96} className="text-on-surface-variant/20 sm:hidden" aria-hidden="true" /><Backpack size={128} className="text-on-surface-variant/20 hidden sm:block" aria-hidden="true" /></>}</div><div className="flex flex-wrap justify-center gap-3"><div className="flex items-center gap-2 px-4 py-2 rounded-full bg-surface-container-highest border border-outline-variant/10"><Icon name={categoryInfo.icon} size={16} className="text-on-surface-variant shrink-0" /><span className="text-sm font-bold text-on-surface uppercase tracking-wider">{categoryInfo.label}</span></div>{rarityLabel && <div className="flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20"><Star size={18} className="text-primary" aria-hidden="true" /><span className="text-sm font-bold text-primary uppercase tracking-wider">{rarityLabel}</span></div>}</div></div>
			<div className="flex-1 space-y-6 relative z-10"><div><h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold font-heading text-on-surface mb-2 leading-tight">{itemName}</h1>{(alternateNames?.en || alternateNames?.ja) && <div className="flex flex-wrap gap-x-4 gap-y-1 mb-4">{alternateNames.en && alternateNames.en !== itemName && <span className="text-sm text-on-surface-variant/70 italic">{alternateNames.en}</span>}{alternateNames.ja && <span className="text-sm text-on-surface-variant/50 font-light">{alternateNames.ja}{japaneseRomanization ? ` (${japaneseRomanization})` : ""}</span>}</div>}{hasDescription ? <div className="max-w-2xl text-on-surface-variant text-base sm:text-lg leading-relaxed whitespace-pre-line">{itemDescription}</div> : <div className="max-w-2xl text-on-surface-variant/50 text-sm italic">Aucune description disponible pour cet objet.</div>}{japaneseDescription && <div className="max-w-2xl text-on-surface-variant/50 text-sm leading-relaxed whitespace-pre-line mt-2 font-light">{japaneseDescription}</div>}</div>
				{bonusEntries.length > 0 && <div><span className="text-[10px] font-bold text-on-surface-variant uppercase block mb-3 opacity-60">Bonus de statistiques</span><StatRows entries={bonusEntries} max={Math.max(...bonusEntries.map(([, value]) => Math.abs(value)))} signed /></div>}
				<div className="flex flex-wrap items-center gap-4">{price != null && price > 0 && <div className="flex items-center gap-2"><Coins size={18} className="text-on-surface-variant" aria-hidden="true" /><span className="text-sm font-bold text-on-surface">{price.toLocaleString("fr-FR")}</span><span className="text-xs text-on-surface-variant">Points</span></div>}{maxStack != null && maxStack > 1 && maxStack < 99999 && <div className="flex items-center gap-2"><Layers size={18} className="text-on-surface-variant" aria-hidden="true" /><span className="text-sm font-bold text-on-surface">{maxStack.toLocaleString("fr-FR")}</span><span className="text-xs text-on-surface-variant">max</span></div>}</div>
				{translatedLocation && !shops?.some((shop) => shop.toLowerCase() === translatedLocation.toLowerCase()) && <div className="flex items-center gap-2"><MapPin size={18} className="text-on-surface-variant" aria-hidden="true" /><span className="text-sm font-medium text-on-surface">{translatedLocation}</span></div>}{bonusEntries.length === 0 && communityEntries.length > 0 && <div><span className="text-[10px] font-bold text-on-surface-variant uppercase block mb-3 opacity-60">Statistiques</span><StatRows entries={communityEntries} max={15} signed={false} /></div>}</div></div>
		{exchangeRecipes?.length ? <section className="bg-surface-container rounded-2xl sm:rounded-[24px] p-4 sm:p-6 border border-border/50"><h2 className="text-xl font-bold mb-4 flex items-center gap-2"><ArrowRightLeft size={24} aria-hidden="true" />Obtention</h2><div className="space-y-3">{exchangeRecipes.map((recipe, index) => <div key={`${recipe.shop}-${index}`} className="p-3 rounded-xl bg-surface-container-low border border-outline-variant/10"><div className="flex items-center gap-2 mb-2"><ShoppingBag size={16} className="text-on-surface-variant shrink-0" aria-hidden="true" /><span className="text-xs font-bold text-on-surface-variant uppercase tracking-wide">{recipe.shop}</span></div><div className="flex flex-wrap gap-2">{recipe.costs.map((cost, costIndex) => <span key={`${cost.code || cost.name}-${costIndex}`} className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-primary/10 text-primary text-xs font-bold border border-primary/20"><span className="text-on-surface font-black">{cost.quantity}x</span>{cost.name}</span>)}</div></div>)}</div></section> : shops?.length ? <section className="bg-surface-container rounded-2xl sm:rounded-[24px] p-4 sm:p-6 border border-border/50"><h2 className="text-xl font-bold mb-4 flex items-center gap-2"><Store size={24} aria-hidden="true" />Boutiques</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{shops.map((shop) => <div key={shop} className="flex items-center gap-3 p-3 rounded-xl bg-surface-container-low hover:bg-surface-container-high transition-colors"><ShoppingBag size={24} className="text-on-surface-variant" aria-hidden="true" /><span className="font-medium text-sm">{shop}</span></div>)}</div></section> : null}
	</div>;
}
