/* GÉNÉRÉ — ne pas éditer à la main.
 * Source : packages/ui/src/styles.css
 * Régénérer : bun packages/ui/scripts/generer-tokens.ts
 *
 * Projection TypeScript des tokens du design system, utilisable HORS navigateur
 * (rendu Canvas du bot Discord, scripts, tests). Module volontairement pur :
 * aucun import, aucune API Node — packages/ui doit rester bundlable côté
 * navigateur, exactement comme la racine de packages/azalee.
 *
 * Les couleurs déclarées en `oklch()` dans le CSS sont converties en
 * hexadécimal sRGB : le backend Skia de Canvas 2D ne sait pas les lire et
 * renvoie `#000000` sans prévenir.
 */

/** Les 4 thèmes unifiés, tels que posés en classe sur `<html>`. */
export const NOMS_THEMES = [
	"theme-roy",
	"theme-gaelle",
	"theme-azalee-light",
	"theme-azalee-dark",
] as const;

export type NomTheme = (typeof NOMS_THEMES)[number];

/** Rôles de couleur Material Design 3 résolus pour un thème donné. */
export type RolesMd3 = Readonly<Record<keyof (typeof THEMES)["theme-roy"]["md3"], string>>;

/** Rôles shadcn (pont MD3 → shadcn) résolus pour un thème donné. */
export type RolesShadcn = Readonly<Record<keyof (typeof THEMES)["theme-roy"]["shadcn"], string>>;

/** Couleurs de marque Rose Griffon — identiques dans les 4 thèmes. */
export const MARQUE = {
	marine: "#0a152c",
	rose: "#f13f8a",
	griffon: "#d8b349",
	brique: "#98483c",
	marineClair: "#1e2f54",
	briqueClair: "#c76c56",
	surMarine: "#f9f8f5",
	succes: "#2e9e52",
	info: "#0089ca",
	alerte: "#e49e22",
} as const;

/** Couleurs imposées par des marques tierces (constantes, hors thème). */
export const MARQUES_TIERCES = {
	discord: "#5865f2",
	patreon: "#ff424d",
	twitch: "#9146ff",
} as const;

/** Échelle de formes M3, en pixels. */
export const FORMES = {
	none: 0,
	extraSmall: 4,
	small: 8,
	medium: 12,
	large: 16,
	extraLarge: 28,
	full: 9999,
} as const;

/** Tokens résolus des 4 thèmes. */
export const THEMES = {
	"theme-roy": {
		md3: {
			primary: "#0e5794",
			onPrimary: "#fafafa",
			primaryContainer: "#a6d2ff",
			onPrimaryContainer: "#000d3b",
			secondary: "#e0b771",
			onSecondary: "#03172c",
			secondaryContainer: "#fae1b8",
			onSecondaryContainer: "#280f00",
			tertiary: "#3179a6",
			onTertiary: "#ffffff",
			tertiaryContainer: "#b4defc",
			onTertiaryContainer: "#001330",
			error: "#e7000b",
			onError: "#ffffff",
			errorContainer: "#ffd6cf",
			onErrorContainer: "#4c0000",
			background: "#f9f4ee",
			onBackground: "#03172c",
			surface: "#f9f4ee",
			onSurface: "#03172c",
			surfaceVariant: "#dbe6f2",
			onSurfaceVariant: "#374a5d",
			outline: "#607489",
			outlineVariant: "#c4cfdb",
			scrim: "#000000",
			shadow: "#000000",
			inverseSurface: "#0d2339",
			inverseOnSurface: "#f5f1ea",
			inversePrimary: "#7cb3eb",
			surfaceDim: "#dbd7d0",
			surfaceBright: "#fefbf8",
			surfaceContainerLowest: "#ffffff",
			surfaceContainerLow: "#f8f5ef",
			surfaceContainer: "#f2eee7",
			surfaceContainerHigh: "#ece7df",
			surfaceContainerHighest: "#e6e0d7",
		},
		shadcn: {
			background: "#f9f4ee",
			foreground: "#03172c",
			card: "#ffffff",
			cardForeground: "#03172c",
			popover: "#ffffff",
			popoverForeground: "#03172c",
			primary: "#0e5794",
			primaryForeground: "#fafafa",
			secondary: "#e0b771",
			secondaryForeground: "#03172c",
			muted: "#f2eee7",
			mutedForeground: "#4d667f",
			accent: "#e0b771",
			accentForeground: "#03172c",
			destructive: "#e7000b",
			destructiveForeground: "#fafafa",
			border: "#d4dfeb",
			input: "#d4dfeb",
			ring: "#0e5794",
			sidebar: "#344e8c",
			sidebarForeground: "#ffffff",
			sidebarPrimary: "#243d5b",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "rgba(255, 196, 110, 0.2)",
			sidebarAccentForeground: "#ffffff",
			sidebarBorder: "rgba(255, 196, 110, 0.3)",
			sidebarRing: "rgba(255, 196, 110, 0.4)",
		},
	},
	"theme-gaelle": {
		md3: {
			primary: "#b32228",
			onPrimary: "#fafafa",
			primaryContainer: "#ffc4bd",
			onPrimaryContainer: "#440000",
			secondary: "#fca676",
			onSecondary: "#550000",
			secondaryContainer: "#ffdac2",
			onSecondaryContainer: "#350000",
			tertiary: "#c9593d",
			onTertiary: "#ffffff",
			tertiaryContainer: "#ffd1c4",
			onTertiaryContainer: "#370000",
			error: "#840015",
			onError: "#ffffff",
			errorContainer: "#ffc3c9",
			onErrorContainer: "#440000",
			background: "#ffe8e0",
			onBackground: "#550000",
			surface: "#ffe8e0",
			onSurface: "#550000",
			surfaceVariant: "#f8d5cf",
			onSurfaceVariant: "#6c3531",
			outline: "#926460",
			outlineVariant: "#e7c5bf",
			scrim: "#000000",
			shadow: "#000000",
			inverseSurface: "#361715",
			inverseOnSurface: "#ffeee8",
			inversePrimary: "#f08f87",
			surfaceDim: "#ead1c9",
			surfaceBright: "#fff1eb",
			surfaceContainerLowest: "#ffffff",
			surfaceContainerLow: "#ffede5",
			surfaceContainer: "#fee5dc",
			surfaceContainerHigh: "#faddd3",
			surfaceContainerHighest: "#f7d6ca",
		},
		shadcn: {
			background: "#ffe8e0",
			foreground: "#550000",
			card: "#ffffff",
			cardForeground: "#550000",
			popover: "#ffffff",
			popoverForeground: "#550000",
			primary: "#b32228",
			primaryForeground: "#fafafa",
			secondary: "#fca676",
			secondaryForeground: "#550000",
			muted: "#f7ded6",
			mutedForeground: "#944a46",
			accent: "#fca676",
			accentForeground: "#550000",
			destructive: "#840015",
			destructiveForeground: "#fafafa",
			border: "#f7ccc4",
			input: "#f7ccc4",
			ring: "#b32228",
			sidebar: "#b03519",
			sidebarForeground: "#ffffff",
			sidebarPrimary: "#770007",
			sidebarPrimaryForeground: "#ffffff",
			sidebarAccent: "rgba(255, 196, 110, 0.2)",
			sidebarAccentForeground: "#ffffff",
			sidebarBorder: "rgba(255, 196, 110, 0.3)",
			sidebarRing: "rgba(255, 196, 110, 0.4)",
		},
	},
	"theme-azalee-light": {
		md3: {
			primary: "#f2a93b",
			onPrimary: "#2a1519",
			primaryContainer: "#ffe08b",
			onPrimaryContainer: "#2a1519",
			secondary: "#a92335",
			onSecondary: "#ffffff",
			secondaryContainer: "#ffdad6",
			onSecondaryContainer: "#410006",
			tertiary: "#2f4f4f",
			onTertiary: "#ffffff",
			tertiaryContainer: "#b1ecec",
			onTertiaryContainer: "#002020",
			error: "#ba1a1a",
			onError: "#ffffff",
			errorContainer: "#ffdad6",
			onErrorContainer: "#93000a",
			background: "#fff8f5",
			onBackground: "#221a15",
			surface: "#fff8f5",
			onSurface: "#221a15",
			surfaceVariant: "#f4ded3",
			onSurfaceVariant: "#52443c",
			outline: "#84746a",
			outlineVariant: "#d7c3b7",
			scrim: "#000000",
			shadow: "#000000",
			inverseSurface: "#382e29",
			inverseOnSurface: "#feede5",
			inversePrimary: "#ffb786",
			surfaceDim: "#e7d7ce",
			surfaceBright: "#fff8f5",
			surfaceContainerLowest: "#ffffff",
			surfaceContainerLow: "#fff1ea",
			surfaceContainer: "#fcebe2",
			surfaceContainerHigh: "#f6e5dc",
			surfaceContainerHighest: "#f0dfd7",
		},
		shadcn: {
			background: "#fff8f5",
			foreground: "#221a15",
			card: "#fff1ea",
			cardForeground: "#221a15",
			popover: "#f6e5dc",
			popoverForeground: "#221a15",
			primary: "#f2a93b",
			primaryForeground: "#2a1519",
			secondary: "#ffdad6",
			secondaryForeground: "#410006",
			muted: "#fcebe2",
			mutedForeground: "#52443c",
			accent: "#b1ecec",
			accentForeground: "#002020",
			destructive: "#ba1a1a",
			destructiveForeground: "#ffffff",
			border: "#d7c3b7",
			input: "#84746a",
			ring: "#f2a93b",
			sidebar: "#fff8f5",
			sidebarForeground: "#221a15",
			sidebarPrimary: "#f2a93b",
			sidebarPrimaryForeground: "#2a1519",
			sidebarAccent: "#b1ecec",
			sidebarAccentForeground: "#002020",
			sidebarBorder: "#d7c3b7",
			sidebarRing: "#f2a93b",
		},
	},
	"theme-azalee-dark": {
		md3: {
			primary: "#ffc66c",
			onPrimary: "#412d00",
			primaryContainer: "#5d4200",
			onPrimaryContainer: "#ffe0aa",
			secondary: "#ffb2be",
			onSecondary: "#5e1123",
			secondaryContainer: "#7c2939",
			onSecondaryContainer: "#ffd9df",
			tertiary: "#edc26e",
			onTertiary: "#422d00",
			tertiaryContainer: "#5e4200",
			onTertiaryContainer: "#ffdea6",
			error: "#ffb4ab",
			onError: "#690005",
			errorContainer: "#93000a",
			onErrorContainer: "#ffdad6",
			background: "#1a120d",
			onBackground: "#ede0db",
			surface: "#1a120d",
			onSurface: "#ede0db",
			surfaceVariant: "#52443c",
			onSurfaceVariant: "#d7c3b7",
			outline: "#9f8d83",
			outlineVariant: "#52443c",
			scrim: "#000000",
			shadow: "#000000",
			inverseSurface: "#ede0db",
			inverseOnSurface: "#1a120d",
			inversePrimary: "#8b5023",
			surfaceDim: "#1a120d",
			surfaceBright: "#413732",
			surfaceContainerLowest: "#140d09",
			surfaceContainerLow: "#221a15",
			surfaceContainer: "#271e19",
			surfaceContainerHigh: "#322823",
			surfaceContainerHighest: "#3d332d",
		},
		shadcn: {
			background: "#1a120d",
			foreground: "#ede0db",
			card: "#221a15",
			cardForeground: "#ede0db",
			popover: "#322823",
			popoverForeground: "#ede0db",
			primary: "#ffc66c",
			primaryForeground: "#412d00",
			secondary: "#7c2939",
			secondaryForeground: "#ffd9df",
			muted: "#271e19",
			mutedForeground: "#d7c3b7",
			accent: "#5e4200",
			accentForeground: "#ffdea6",
			destructive: "#ffb4ab",
			destructiveForeground: "#690005",
			border: "#52443c",
			input: "#9f8d83",
			ring: "#ffc66c",
			sidebar: "#1a120d",
			sidebarForeground: "#ede0db",
			sidebarPrimary: "#ffc66c",
			sidebarPrimaryForeground: "#412d00",
			sidebarAccent: "#5e4200",
			sidebarAccentForeground: "#ffdea6",
			sidebarBorder: "#52443c",
			sidebarRing: "#ffc66c",
		},
	},
} as const;

/** Renvoie les rôles MD3 d'un thème. */
export function md3(nom: NomTheme): RolesMd3 {
	return THEMES[nom].md3;
}

/** Renvoie les rôles shadcn d'un thème. */
export function shadcn(nom: NomTheme): RolesShadcn {
	return THEMES[nom].shadcn;
}
