// Auto-generated by Parser Generator
// Format: .utf
// Source: FUN_14067d35c

using System;
using System.Buffers.Binary;
using System.IO;
using System.Runtime.InteropServices;

namespace IECODE.Core.Formats.Criware
{
    /// <summary>
    /// Header for format .utf
    /// </summary>
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public readonly struct UtftableHeader
    {
        public readonly uint Magic;
        public readonly uint TableSize;
        public readonly ushort Version;
        public readonly ushort RowsOffset;
        public readonly uint StringTableOffset;
        public readonly uint DataOffset;
        public readonly uint TableNameOffset;
        public readonly ushort NumColumns;
        public readonly ushort RowLength;
        public readonly uint NumRows;

        public bool IsValid => Magic == 0x40555446;
    }

    /// <summary>
    /// AOT-compatible parser for .utf
    /// </summary>
    public static class UtftableParser
    {
        public const uint MAGIC = 0x40555446;  // "@UTF"

        public static UtftableHeader ParseHeader(ReadOnlySpan<byte> data)
        {
            if (data.Length < Marshal.SizeOf<UtftableHeader>())
                throw new InvalidDataException("Data too small");

            ref readonly var header = ref MemoryMarshal.AsRef<UtftableHeader>(data);

            if (!header.IsValid)
                throw new InvalidDataException($"Invalid magic: 0x{header.Magic:X8}");

            return header;
        }

        public static UtftableHeader ParseFile(string path)
            => ParseHeader(File.ReadAllBytes(path));
    }
}
