import type { Metadata } from "next";
import Image from "next/image";
import { Suspense } from "react";
import { AnimatedSection } from "@/components/home/AnimatedSection";
import { LandingHero } from "@/components/home/LandingHero";
import { LatestNewsSection } from "@/components/home/LatestNewsSection";
import { NetworkSection } from "@/components/home/NetworkSection";
import { ToolsPreview } from "@/components/home/ToolsPreview";
import { WikiCarousel } from "@/components/home/WikiCarousel";
import type { WikiSectionStats } from "@/components/home/WikiCarousel";
import { getPgPool } from "@/lib/db/pg";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = {
	alternates: { canonical: "/" },
	description:
		"L'information la plus précise autour d'Inazuma Eleven. Stats, techniques, et actualités en français.",
	openGraph: {
		title: "Azalée - Inazuma Eleven: Victory Road",
		description:
			"L'information la plus précise autour d'Inazuma Eleven. Stats, techniques, et actualités en français.",
		url: "https://azalee.rosegriffon.fr",
		siteName: "Azalée",
		locale: "fr_FR",
		type: "website",
		// OG image is auto-generated by opengraph-image.tsx
	},
	title: "Azalée - Inazuma Eleven: Victory Road",
	twitter: {
		card: "summary_large_image",
		creator: "@Azalee_IE",
		description: "L'information la plus précise autour d'Inazuma Eleven.",
		site: "@Azalee_IE",
		title: "Azalée - Inazuma Eleven: Victory Road",
	},
};

export const revalidate = 300; // Cache for 5 minutes

export default async function HomePage() {
	const supabase = await createClient();
	const pool = getPgPool();

	// Fetch pinned articles, latest articles, tweets, and wiki counts in parallel
	// Lecture `articles` + `tweets` Postgres DIRECTE (bypass le Data API PostgREST
	// — cf. lib/db/pg.ts) ; `inagle_*` reste sur le client Supabase (Proxy SQLite,
	// cf. lib/supabase/server.ts).
	const [
		{ rows: pinnedArticles },
		{ rows: latestArticles },
		{ rows: latestTweets },
		{ count: charactersCount },
		{ count: skillsCount },
		{ count: itemsCount },
		{ count: keshinsCount },
		{ count: soulsCount },
		{ count: passivesCount },
	] = await Promise.all([
		pool.query(
			`SELECT * FROM articles
			 WHERE status = $1 AND app = $2
			 ORDER BY published_at DESC
			 LIMIT 1`,
			["published", "azalee"]
		),
		pool.query(
			`SELECT * FROM articles
			 WHERE status = $1 AND app = $2
			 ORDER BY published_at DESC
			 LIMIT 3 OFFSET 1`,
			["published", "azalee"]
		),
		pool.query(
			`SELECT id, text, translation, created_at, author_username, author_name, media
			 FROM tweets
			 WHERE author_username = $1
			 ORDER BY created_at DESC
			 LIMIT 6`,
			["Azalee_IE"]
		),
		supabase.from("inagle_characters").select("id", { count: "exact", head: true }),
		supabase.from("inagle_skills").select("id", { count: "exact", head: true }),
		supabase.from("inagle_items").select("id", { count: "exact", head: true }),
		supabase.from("inagle_keshins_clean").select("id", { count: "exact", head: true }),
		supabase.from("inagle_souls_clean").select("id", { count: "exact", head: true }),
		supabase.from("inagle_passives").select("id", { count: "exact", head: true }),
	]);

	// Merge: pinned first, then fill remaining slots with latest (up to 3 total)
	const pinned = (pinnedArticles || []) as any[];
	const latest = (latestArticles || []) as any[];
	const standardNews = [...pinned, ...latest].slice(0, 3);
	const recentTweets = (latestTweets || []) as any[];

	const wikiStats: WikiSectionStats = {
		characters: charactersCount ?? 0,
		items: itemsCount ?? 0,
		keshins: keshinsCount ?? 0,
		passives: passivesCount ?? 0,
		skills: skillsCount ?? 0,
		souls: soulsCount ?? 0,
	};

	const jsonLd = [
		{
			"@context": "https://schema.org",
			"@type": "WebSite",
			alternateName: "Azalee Inazuma Eleven Wiki",
			description:
				"Base de données complète Inazuma Eleven: Victory Road. Personnages, techniques, objets et actualités en français.",
			inLanguage: "fr",
			name: "Azalée",
			potentialAction: {
				"@type": "SearchAction",
				"query-input": "required name=search_term_string",
				target: {
					"@type": "EntryPoint",
					urlTemplate: "https://azalee.rosegriffon.fr/search?q={search_term_string}",
				},
			},
			publisher: {
				"@type": "Organization",
				logo: {
					"@type": "ImageObject",
					url: "https://azalee.rosegriffon.fr/icon.webp",
				},
				name: "Rose Griffon",
				url: "https://rosegriffon.fr",
				founder: {
					"@type": "Person",
					name: "yoyo",
					alternateName: "yoyo",
					url: "https://x.com/yoyo__goat",
					sameAs: ["https://x.com/yoyo__goat"],
				},
			},
			url: "https://azalee.rosegriffon.fr",
		},
		{
			"@context": "https://schema.org",
			"@type": "VideoGame",
			alternateName: [
				"Inazuma Eleven: Heroes' Great Road",
				"Inazuma Eleven: Eiyuutachi no Great Road",
			],
			applicationCategory: "Game",
			description:
				"Jeu de football RPG développé par Level-5. Recrutez des joueurs, maîtrisez les techniques spéciales et menez votre équipe à la victoire.",
			developer: {
				"@type": "Organization",
				name: "Level-5",
			},
			gamePlatform: ["Nintendo Switch", "PlayStation 4", "PlayStation 5"],
			genre: ["Sports", "RPG", "Football"],
			inLanguage: ["ja", "en", "fr", "de", "it", "es", "pt", "zh"],
			name: "Inazuma Eleven: Victory Road",
			publisher: {
				"@type": "Organization",
				name: "Level-5",
				url: "https://www.level5.co.jp/",
			},
			url: "https://www.inazuma.jp/",
		},
	];

	return (
		<div className="animate-in fade-in duration-700">
			<script
				type="application/ld+json"
				dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
			/>

			{/* Dynamic Landing Hero */}
			<LandingHero stats={wikiStats} />

			{/* Main Content Anchor */}
			<div
				id="home-content"
				className="space-y-6 md:space-y-12 pb-20 mt-8 md:mt-16 max-w-[1800px] mx-auto scroll-mt-24"
			>
				{/* Latest News (3 items) */}
				<AnimatedSection direction="up">
					<section className="md:px-8 lg:px-12">
						<Suspense
							fallback={<div className="h-96 animate-pulse bg-surface-container rounded-3xl" />}
						>
							<LatestNewsSection articles={standardNews} tweets={recentTweets} />
						</Suspense>
					</section>
				</AnimatedSection>

				{/* Interactive Tools Preview */}
				<AnimatedSection direction="up" delay={0.05}>
					<section className="md:px-8 lg:px-12">
						<ToolsPreview />
					</section>
				</AnimatedSection>

				{/* Section Divider */}
				<div className="flex items-center gap-4 px-8 md:hidden" aria-hidden="true">
					<div className="flex-1 h-px bg-outline-variant/20" />
					<Image src="/logo.webp" alt="" width={20} height={20} className="size-5 opacity-30" />
					<div className="flex-1 h-px bg-outline-variant/20" />
				</div>

				{/* Wiki Carousel */}
				<AnimatedSection direction="scale" delay={0.1}>
					<WikiCarousel stats={wikiStats} />
				</AnimatedSection>

				{/* Réseau Rose Griffon : association (site principal) + Achilléa (compétitif) */}
				<AnimatedSection direction="up" delay={0.05}>
					<NetworkSection />
				</AnimatedSection>
			</div>
		</div>
	);
}
