#!/usr/bin/env python3
"""Regenerate `data/re/menu-icon-atlases.txt` — the list of menu icon-atlas g4tx paths.

The decompiled menu Lua passes texture references to funcLua sprite commands as CRC32 hashes of
the FULL logical g4tx VFS path (e.g. CRC32("#/menu/200_icon/05_icon_rarity/<LG>/icon_rarity.g4tx")).
The recovered crc32 name dictionary reverses those hashes back to their path strings. This script
scans every decompiled Lua script for integer literals, reverses each via the dictionary, and keeps
the ones that resolve to a `.g4tx` path — i.e. every atlas the menu scripts actually reference.

That list feeds `nie-game --build-region-index`, which indexes each atlas's region names ->
(g4tx file, rect) so render-from-runtime can resolve a runtime `spriteRegion` to real pixels.

These artifacts are gitignored (under data/); this regenerates them from the in-repo corpus
(data/lua_scripts/ + data/re/menu-crc32-dictionary.json) — no remote, no network. Pure stdlib.

Usage: python3 scripts/extract_menu_icon_atlases.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DICT = ROOT / "data/re/menu-crc32-dictionary.json"
LUA = ROOT / "data/lua_scripts/decompiled"
OUT = ROOT / "data/re/menu-icon-atlases.txt"

# Integer literals in the decompiled Lua (>= 6 digits filters out indices/small constants;
# real CRC32 path hashes are 32-bit so up to 10 digits).
INT = re.compile(r"\b(\d{6,10})\b")


def main():
    names = {int(k, 16): v for k, v in json.loads(DICT.read_text()).items()}
    atlases = set()
    for f in LUA.rglob("*.lua"):
        for m in INT.finditer(f.read_text(errors="ignore")):
            v = int(m.group(1))
            if v > 0xFFFFFFFF:
                continue
            name = names.get(v)
            if name and name.endswith(".g4tx"):
                atlases.add(name)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "# Menu icon-atlas g4tx paths referenced by the decompiled menu Lua.",
        "# Regenerated by scripts/extract_menu_icon_atlases.py (reverse CRC32 path-hashes via dict).",
        "# One logical VFS g4tx path per line. Consumed by `nie-game --build-region-index`.",
    ]
    OUT.write_text("\n".join(header + sorted(atlases)) + "\n")
    print(f"menu icon atlases: {len(atlases)} g4tx paths -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
