/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmgame_free: (a: number, b: number) => void;
export const audio_to_wav: (a: number, b: number) => [number, number, number, number];
export const aura_lookup: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const calculate_stats: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const cfgbin_parse_json: (a: number, b: number) => [number, number, number, number];
export const cfgbin_typed_json: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const cpk_extract_file: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const cpk_parse_entries: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const crilayla_decompress: (a: number, b: number) => [number, number, number, number];
export const detect_format: (a: number, b: number) => [number, number];
export const final_score: (a: number, b: number) => number;
export const g4md_parse_json: (a: number, b: number) => [number, number, number, number];
export const g4mg_extract_json: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const g4pk_parse_json: (a: number, b: number) => [number, number, number, number];
export const g4tx_info_json: (a: number, b: number) => [number, number, number, number];
export const g4tx_named_to_png: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const g4tx_sprite_sheet_json: (a: number, b: number) => [number, number, number, number];
export const g4tx_to_png: (a: number, b: number) => [number, number, number, number];
export const is_lua_bytecode: (a: number, b: number) => number;
export const item_lookup: (a: number, b: number) => [number, number, number, number];
export const lip_to_json: (a: number, b: number) => [number, number, number, number];
export const lua_bytecode_json: (a: number, b: number) => [number, number, number, number];
export const match_tick: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const model_to_glb: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const parse_save_json: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const rarity_to_growth_rank: (a: number) => number;
export const single_stat: (a: number, b: number, c: number, d: number, e: number) => number;
export const skill_lookup: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const utf_table_json: (a: number, b: number) => [number, number, number, number];
export const wasmgame_height: (a: number) => number;
export const wasmgame_in_match: (a: number) => number;
export const wasmgame_input: (a: number, b: number, c: number) => void;
export const wasmgame_new: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasmgame_render: (a: number) => [number, number];
export const wasmgame_score: (a: number) => [number, number];
export const wasmgame_update: (a: number, b: number) => void;
export const wasmgame_width: (a: number) => number;
export const __wasm_start: () => void;
export const init_panic_hook: () => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
