// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Racine de jeu par défaut — VRAIE détection (registre Steam + bibliothèques +
	 *  `appmanifest_2799860.acf`, cf. [`resolve_game_dir_native`]), pas un chemin deviné.
	 */
	defaultGameDir: () => __TAURI_INVOKE<string>("default_game_dir"),
	/**  Vérifie qu'un répertoire de jeu est valide (contient `data/cpk_list.cfg.bin`). */
	checkGameDir: (gameDir: string) => __TAURI_INVOKE<boolean>("check_game_dir", { gameDir }),
	/**
	 *  Résout le miroir SQLite (`supabase-*.sqlite`) par défaut — même ordre de résolution que
	 *  [`nie_wiki::mirror::resolve`] (`NIE_WIKI_DB`/`SQLITE_DB_PATH`, fichier le plus récent), mais
	 *  avec un répertoire de backups RÉEL pour cette appli desktop (`<racine du jeu>/var/wiki-mirror`,
	 *  où vit effectivement `supabase-2026-06-05T00-08-26.sqlite` sur ce poste) plutôt que le chemin
	 *  de dev WSL codé en dur `/home/ubuntu/niers/data/backups` (inexistant hors de la machine de
	 *  développement). Renvoie `None` si rien n'est trouvé — jamais un chemin deviné : le champ
	 *  « Base SQLite » des Paramètres reste alors vide, à renseigner manuellement.
	 */
	defaultWikiDb: (gameDir: string | null) => __TAURI_INVOKE<string | null>("default_wiki_db", { gameDir }),
	/**
	 *  Résout `var/niers.sqlite` (base RE — fonctions/classes RTTI/xrefs labellisées par `nie-re`,
	 *  cf. `src/lib/reDb.ts`) sous la racine du jeu. Commande Rust plutôt qu'un `exists()` JS
	 *  (`@tauri-apps/plugin-fs`) : la portée `fs:scope` de l'app ne couvre que `$APPDATA`, un
	 *  `std::fs` Rust n'a pas cette restriction — même raison que [`default_wiki_db`] au-dessus.
	 */
	defaultReDb: (gameDir: string | null) => __TAURI_INVOKE<string | null>("default_re_db", { gameDir }),
	/**
	 *  Force le (re)chargement du VFS en cache — appelé une fois au démarrage du frontend pour
	 *  amortir le coût d'indexation AVANT la première navigation (cf. demande utilisatrice
	 *  « précharge le VFS au chargement pour éviter la latence ensuite »). Renvoie les mêmes
	 *  statistiques que [`vfs_stats`] pour un toast de confirmation côté UI.
	 */
	preloadVfs: (gameDir: string | null) => typedError<StatsDto, string>(__TAURI_INVOKE("preload_vfs", { gameDir })),
	vfsLs: (prefix: string, gameDir: string | null) => typedError<LsDto, string>(__TAURI_INVOKE("vfs_ls", { prefix, gameDir })),
	vfsFind: (query: string, ext: string | null, limit: number, gameDir: string | null) => typedError<EntryDto[], string>(__TAURI_INVOKE("vfs_find", { query, ext, limit, gameDir })),
	vfsStats: (gameDir: string | null) => typedError<StatsDto, string>(__TAURI_INVOKE("vfs_stats", { gameDir })),
	/**
	 *  Métadonnées d'une seule entrée VFS (`None` si le chemin n'existe pas) — sert notamment à
	 *  savoir si un fichier est "loose" (`cpk` vide) donc éditable EN PLACE via [`vfs_write_b64`],
	 *  sans devoir refaire transiter tout l'index (`vfs_ls`/`vfs_all_entries`) pour un seul chemin.
	 */
	vfsEntryMeta: (path: string, gameDir: string | null) => typedError<{
	path: string,
	name: string,
	size: number,
	cpk: string,
} | null, string>(__TAURI_INVOKE("vfs_entry_meta", { path, gameDir })),
	/**
	 *  Aperçu structuré d'une entrée : résumé par format ([`nie_explore::describe_content`]) +
	 *  les 64 premiers octets en hex (pour un magic visible même sans décodeur dédié).
	 */
	vfsDescribe: (path: string, gameDir: string | null) => typedError<string[], string>(__TAURI_INVOKE("vfs_describe", { path, gameDir })),
	/**
	 *  Contenu brut, borné à `max_bytes` (défaut 2 MiB) pour rester raisonnable sur l'IPC JSON —
	 *  utiliser `vfs_extract_to` pour les gros fichiers (écriture disque directe côté Rust).
	 */
	vfsReadB64: (path: string, gameDir: string | null, maxBytes: number | null) => typedError<string, string>(__TAURI_INVOKE("vfs_read_b64", { path, gameDir, maxBytes })),
	/**  Décode la meilleure texture d'un `.g4tx` en PNG (base64), pour un `<img>` côté UI. */
	vfsTexturePngB64: (path: string, gameDir: string | null) => typedError<string, string>(__TAURI_INVOKE("vfs_texture_png_b64", { path, gameDir })),
	/**  Extrait un fichier VFS directement vers `dest` (écriture Rust→disque, pas de round-trip JS). */
	vfsExtractTo: (path: string, dest: string, gameDir: string | null) => typedError<number, string>(__TAURI_INVOKE("vfs_extract_to", { path, dest, gameDir })),
	/**
	 *  Écrit `data_b64` EN PLACE sur un fichier VFS "loose" (physiquement présent sur disque sous
	 *  `<jeu>/<chemin>`, PAS empaqueté dans un CPK — `entry.cpk` vide côté `EntryDto`/`VfsEntry`,
	 *  cf. `Vfs::read` § « CPK vide → fichier loose ») — contrairement à [`vfs_extract_to`]/
	 *  [`save_bytes_b64`] qui exportent toujours vers une destination choisie par l'utilisatrice.
	 *  Refuse explicitement les entrées empaquetées dans un CPK : `nie-formats` n'a pas d'encodeur
	 *  CPK, y écrire corromprait l'archive — même contrainte que partout ailleurs dans ce fichier,
	 *  vérifiée ICI plutôt que suppposée (le VFS sait exactement quelles entrées sont loose).
	 */
	vfsWriteB64: (path: string, dataB64: string, gameDir: string | null) => typedError<number, string>(__TAURI_INVOKE("vfs_write_b64", { path, dataB64, gameDir })),
	/**
	 *  Écrit `data_b64` comme fichier "loose" AU MÊME CHEMIN qu'une entrée normalement empaquetée
	 *  dans un CPK — contournement de l'absence d'encodeur CPK, PAS une écriture confirmée : le
	 *  comportement réel de `nie.exe` face à un fichier loose à la place d'un CPK-packed n'est **pas
	 *  confirmé par rétro-ingénierie** (même incertitude déjà documentée pour l'export de mod
	 *  « overlay loose-file » dans `modWorkspace.ts`/`exportMod`). Le jeu peut tout simplement
	 *  ignorer ce fichier et continuer à lire le CPK. Confirmation explicite déjà exigée côté UI
	 *  avant l'appel (EAC présent sur cette installation).
	 */
	vfsWriteLooseOverrideB64: (path: string, dataB64: string, gameDir: string | null) => typedError<number, string>(__TAURI_INVOKE("vfs_write_loose_override_b64", { path, dataB64, gameDir })),
	/**
	 *  Écrit des octets édités (base64, depuis l'éditeur hex de l'UI) vers `dest` — n'écrit
	 *  JAMAIS dans un CPK : `nie-formats` n'a pas d'encodeur CPK, donc « éditer » un asset du
	 *  jeu produit toujours une copie externe, jamais une modification en place des packs.
	 */
	saveBytesB64: (dest: string, dataB64: string) => typedError<number, string>(__TAURI_INVOKE("save_bytes_b64", { dest, dataB64 })),
	/**
	 *  Chemins VFS dont le nom (sans extension) est CONTENU dans `needle`, insensible à la casse —
	 *  substring en mémoire, fallback historique tant que l'index SQL ([`vfs_all_entries`] +
	 *  `vfsIndexDb`) n'a pas été construit côté frontend.
	 */
	vfsRelated: (needle: string, limit: number, gameDir: string | null) => typedError<EntryDto[], string>(__TAURI_INVOKE("vfs_related", { needle, limit, gameDir })),
	/**
	 *  Scanne la totalité du VFS (~255 800 entrées) — utilisé par `vfsIndexDb.reindex` (frontend)
	 *  pour matérialiser un index SQL persistant (`vfs_files`, table gérée par `tauri-plugin-sql`)
	 *  permettant une résolution EXACTE par code interne (segment de chemin), plus précise que le
	 *  `.contains()` substring en mémoire de [`vfs_related`] (qui peut matcher un code interne
	 *  apparaissant par hasard ailleurs dans un chemin non lié).
	 */
	vfsAllEntries: (gameDir: string | null) => typedError<EntryDto[], string>(__TAURI_INVOKE("vfs_all_entries", { gameDir })),
	/**
	 *  Liste toutes les techniques du jeu (`nie_data::skill`, cf. `game_data.rs`) — première
	 *  donnée de jeu STATIQUE câblée depuis `nie-data` (dépendance déclarée mais jamais utilisée
	 *  avant), via le pont déjà existant `nie_explore::bridge` (même moteur que `niers vfs cat`).
	 */
	gameDataSkills: (gameDir: string | null) => typedError<SkillDto[], string>(__TAURI_INVOKE("game_data_skills", { gameDir })),
	/** Objets (armes/consommables/costumes/…, `nie_data::item`) — même patron que `gameDataSkills`. */
	gameDataItems: (gameDir: string | null) => typedError<ItemDto[], string>(__TAURI_INVOKE("game_data_items", { gameDir })),
	/** Avatar/Keshin (`nie_data::aura`) — même patron que `gameDataSkills`. */
	gameDataAuras: (gameDir: string | null) => typedError<AuraDto[], string>(__TAURI_INVOKE("game_data_auras", { gameDir })),
	/** Succès (`nie_data::trophy`) — même patron que `gameDataSkills`. */
	gameDataTrophies: (gameDir: string | null) => typedError<TrophyDto[], string>(__TAURI_INVOKE("game_data_trophies", { gameDir })),
	/** Quêtes (`nie_data::quest`) — même patron que `gameDataSkills`. */
	gameDataQuests: (gameDir: string | null) => typedError<QuestDto[], string>(__TAURI_INVOKE("game_data_quests", { gameDir })),
	/** Personnages sélectionnables pour le calculateur de stats — même patron que `gameDataSkills`. */
	gameDataCharaPicker: (gameDir: string | null) => typedError<CharaPickerDto[], string>(__TAURI_INVOKE("game_data_chara_picker", { gameDir })),
	/**
	 *  Calcule les stats d'un personnage (§4.2 roadmap) — `nie_core::growth::calculate_stats` sur
	 *  les tables de croissance IEVR embarquées. `rarityCode` : 0=N, 2=R, 3=SR, 4=SSR, 5=UR, 6=LR,
	 *  7=Legend, 20=BASARA.
	 */
	gameDataCalculateStats: (charaParamId: string, level: number, rarityCode: number, gameDir: string | null) =>
		typedError<StatBlockDto, string>(__TAURI_INVOKE("game_data_calculate_stats", { charaParamId, level, rarityCode, gameDir })),
	/**
	 *  Décode N'IMPORTE QUEL `.cfg.bin` du VFS (RDBN *ou* T2B, détecté automatiquement via
	 *  [`nie_formats::cfgbin::is_rdbn`]) vers la forme JSON "inagle" — couvre TOUS les fichiers de
	 *  configuration du jeu (personnages, objets, techniques, auras, boutiques, quêtes, trophées,
	 *  tactiques, capsules, costumes… plusieurs centaines de fichiers dans `data/common/gamedata/`
	 *  et `data/common/text/`), pas seulement les quelques modules `nie-data` câblés individuellement
	 *  avec un DTO typé (`game_data.rs`) — cf. demande utilisatrice « niers doit couvrir tout
	 *  nie.exe ». Générique : aucun parseur par format à écrire, juste le pont déjà
	 *  vérifié [`nie_explore::bridge`] (même moteur que `niers vfs cat`).
	 */
	vfsDecodeCfgbin: (path: string, gameDir: string | null) => typedError<unknown, string>(__TAURI_INVOKE("vfs_decode_cfgbin", { path, gameDir })),
	/**
	 *  Ré-encode du JSON édité (forme "inagle" `{"entries":[...]}` T2B **ou** `{"lists":[...]}`
	 *  RDBN, dispatch automatique symétrique à [`vfsDecodeCfgbin`]) vers un `.cfg.bin` binaire
	 *  VALIDE.
	 *
	 *  - T2B : `nie_formats::cfgbin::encode_t2b`, reconstruction libre à partir du JSON seul.
	 *  - RDBN : `nie_formats::cfgbin::encode_rdbn` + `nie_explore::bridge::json_to_rdbn_lists`, qui a
	 *    besoin de l'ORIGINAL déjà décodé comme gabarit — c'est un *patch* de valeurs, pas une
	 *    reconstruction libre : le JSON seul perd l'information de type par colonne (ex. Short/
	 *    ActType ou Rates/Position sont indiscernables une fois sérialisés). D'où `path` en plus de
	 *    `json` ici : on relit et reparse le fichier original depuis le VFS pour fournir ce gabarit.
	 *
	 *  Les deux encodeurs sont vérifiés par round-trip réel sur des centaines/milliers de vrais
	 *  fichiers du jeu (`cfgbin.rs` : `encode_t2b_round_trip_sur_le_vrai_jeu`,
	 *  `encode_rdbn_round_trip_sur_le_vrai_jeu` ; `bridge.rs` : `json_bridge_round_trip_sur_le_vrai_jeu`,
	 *  `json_bridge_rdbn_round_trip_sur_le_vrai_jeu`), pas devinés.
	 *
	 *  Renvoie les octets en base64 : compose avec [`vfs_write_b64`]/
	 *  [`vfs_write_loose_override_b64`]/[`save_bytes_b64`] côté frontend pour l'écriture réelle —
	 *  pas de nouvelle commande d'écriture, réutilisation de celles qui existent déjà.
	 */
	encodeCfgbinConfig: (path: string, json: string, gameDir: string | null) => typedError<string, string>(__TAURI_INVOKE("encode_cfgbin_config", { path, json, gameDir })),
	/**
	 *  Liste les VRAIS fichiers `.cpk` physiquement présents sous `<racine>/data/packs/` — le VFS
	 *  n'expose JAMAIS ces conteneurs comme des entrées navigables (`vfs_ls`/`vfs_all_entries` ne
	 *  listent que les chemins internes du jeu, ex. `data/common/...`, jamais `data/packs/*.cpk`
	 *  eux-mêmes), donc naviguer vers `data/packs` dans l'Explorateur y paraissait vide/« non
	 *  préchargé » alors que les fichiers sont bien là — cette commande comble ce trou en lisant le
	 *  vrai dossier, pour un pont direct vers [`open_raw_cpk`]/l'onglet CPK brut.
	 */
	listPacksDir: (gameDir: string | null) => typedError<PackFileDto[], string>(__TAURI_INVOKE("list_packs_dir", { gameDir })),
	/**
	 *  Ouvre un fichier `.cpk` quelconque du disque (chemin absolu choisi par l'utilisatrice) et
	 *  renvoie la liste de ses entrées — met à jour [`RawCpkState`] pour les commandes suivantes.
	 */
	openRawCpk: (path: string) => typedError<RawCpkEntryDto[], string>(__TAURI_INVOKE("open_raw_cpk", { path })),
	/**
	 *  Aperçu structuré d'une entrée du CPK brut ouvert (même moteur que [`vfs_describe`]) — extrait
	 *  et décompresse d'abord via [`CpkReader::extract`].
	 */
	rawCpkDescribe: (index: number) => typedError<string[], string>(__TAURI_INVOKE("raw_cpk_describe", { index })),
	/**  Contenu brut d'une entrée du CPK ouvert, borné (même plafond par défaut que [`vfs_read_b64`]). */
	rawCpkReadB64: (index: number, maxBytes: number | null) => typedError<string, string>(__TAURI_INVOKE("raw_cpk_read_b64", { index, maxBytes })),
	/**  Extrait une entrée du CPK ouvert vers `dest` (écriture Rust→disque directe). */
	rawCpkExtractTo: (index: number, dest: string) => typedError<number, string>(__TAURI_INVOKE("raw_cpk_extract_to", { index, dest })),
	/**
	 *  Extrait TOUTES les entrées du CPK ouvert vers `dest_dir`, en préservant l'arborescence
	 *  `directory/filename` d'origine (mécanique identique à [`rawCpkExtractTo`], en boucle sur
	 *  `RawCpkState.entries`) — évite d'extraire un CPK entier une entrée à la fois depuis l'UI.
	 *  Renvoie `(n_ok, n_err)` : les échecs individuels (entrée corrompue/compression non supportée)
	 *  n'interrompent pas le reste de l'extraction, pour ne pas perdre tout le travail sur 1 entrée.
	 */
	rawCpkExtractAll: (destDir: string) => typedError<[number, number], string>(__TAURI_INVOKE("raw_cpk_extract_all", { destDir })),
	/**
	 *  Rend une fois le chemin passé en argument au lancement (`argv[1]`), puis se vide — le
	 *  frontend l'appelle une seule fois au démarrage pour savoir s'il doit ouvrir un fichier
	 *  « externe » (hors VFS, ex. un `.g4tx` déjà extrait sur disque) plutôt que la racine du VFS.
	 */
	takePendingOpen: () => __TAURI_INVOKE<string | null>("take_pending_open"),
	/**
	 *  Resynchronise le chrome natif Windows 11 (Mica, barre de titre/légende) sur le thème
	 *  clair/sombre choisi côté frontend (`next-themes`, `resolvedTheme`) — corrige le fait que le
	 *  chrome natif restait figé en sombre même si l'utilisatrice bascule en clair dans Paramètres.
	 *  No-op silencieux hors Windows 11.
	 */
	setTitlebarTheme: (dark: boolean) => typedError<null, string>(__TAURI_INVOKE("set_titlebar_theme", { dark })),
	/**
	 *  Aperçu structuré d'un fichier QUELCONQUE du disque (pas du VFS) — utilisé par « Ouvrir
	 *  avec nie-explorer » sur un fichier déjà extrait/exporté.
	 */
	describeDiskFile: (path: string) => typedError<string[], string>(__TAURI_INVOKE("describe_disk_file", { path })),
	readDiskFileB64: (path: string, maxBytes: number | null) => typedError<string, string>(__TAURI_INVOKE("read_disk_file_b64", { path, maxBytes })),
	/**
	 *  `true` si `path` désigne un FICHIER (pas un dossier) existant sur disque — hors de toute
	 *  portée `fs:scope` JS (même famille que [`describeDiskFile`], `std::fs` direct). Utilisé pour
	 *  valider un chemin venu du presse-papiers (Ctrl+V, cf. [`copyDiskFileToAppdata`]) : le
	 *  plugin `fs` JS `exists()` est scopé à `$APPDATA/**` et renverrait faux/erreur sur un chemin
	 *  disque quelconque, alors que c'est justement le cas normal ici.
	 */
	diskFileExists: (path: string) => __TAURI_INVOKE<boolean>("disk_file_exists", { path }),
	/**
	 *  Copie un fichier disque ARBITRAIRE (hors de toute portée `fs:scope` JS — même famille que
	 *  [`readDiskFileB64`]/[`describeDiskFile`], `std::fs` direct) vers un chemin relatif sous
	 *  `AppData` (espace de travail des mods, `mods/<modId>/…`, JS `modWorkspace.ts`). Utilisé par
	 *  le VRAI Ctrl+V (`editBus.paste()` → `stageReplacementFromPath`) : la source vient du
	 *  presse-papiers, pas d'un sélecteur natif — elle n'a donc PAS la portée temporaire que Tauri
	 *  accorde aux chemins choisis via `@tauri-apps/plugin-dialog`, et le plugin `fs` JS (portée =
	 *  `$APPDATA/**` seulement) refuserait de la lire. `dest_appdata_rel` DOIT rester sous
	 *  `AppData` (jamais le dossier du jeu).
	 */
	copyDiskFileToAppdata: (src: string, destAppdataRel: string) => typedError<number, string>(__TAURI_INVOKE("copy_disk_file_to_appdata", { src, destAppdataRel })),
	/**
	 *  Remplace la texture d'un `.g4tx` **mono-texture, sans région d'atlas** (§2.2 roadmap) par
	 *  un PNG choisi — décode le PNG, l'encode en DDS BGRA8 + conteneur G4TX, écrit directement
	 *  dans l'espace de travail du mod. Rejette explicitement les atlas multi-région.
	 */
	stageTextureReplacement: (vfsPath: string, pngSrcPath: string, destAppdataRel: string, gameDir: string | null) =>
		typedError<number, string>(__TAURI_INVOKE("stage_texture_replacement", { vfsPath, pngSrcPath, destAppdataRel, gameDir })),
	/**
	 *  Exporte les fichiers d'un mod en un `.cpk` **autonome, non chiffré, non compressé**
	 *  (§1.2 roadmap) — cf. `nie_formats::cpk_encode` pour la portée exacte et ses limites
	 *  documentées (vérifié par round-trip contre `CpkReader`, PAS par chargement réel dans
	 *  `nie.exe`).
	 */
	exportModAsCpk: (files: CpkExportFileDto[], dest: string) => typedError<number, string>(__TAURI_INVOKE("export_mod_as_cpk", { files, dest })),
	/**
	 *  Extrait `path` (+ ses fichiers frères de même basename dans le même dossier VFS : g4mg/g4sk/
	 *  g4tx/g4mt) vers un dossier temporaire, lance Blender avec un script d'amorçage qui active
	 *  l'addon `tools/niers` (`bpy.utils` via `sys.path`, sans dépendre du dossier d'addons
	 *  utilisateur Blender) puis pré-charge le modèle via son opérateur natif
	 *  `level5_g4_port.load_original_model` (le même que « File > Import » appellerait).
	 *  Pose `NIE_GAME_DIR` dans l'environnement du process Blender : le panneau de recherche
	 *  niers→Blender (`niers_bridge.py`) l'utilise pour retrouver `niers.exe` et le VFS sans deviner.
	 */
	openInBlender: (path: string, blenderExe: string | null, gameDir: string | null) => typedError<string, string>(__TAURI_INVOKE("open_in_blender", { path, blenderExe, gameDir })),
	/**
	 *  Recherche de personnages via le GraphQL azalee (`characters(q, limit)`), en bonus du miroir
	 *  local `nie-wiki` — utile quand aucun `supabase-*.sqlite` local n'est configuré.
	 */
	remoteSearchChara: (baseUrl: string, query: string) => typedError<unknown, string>(__TAURI_INVOKE("remote_search_chara", { baseUrl, query })),
	/**  Recherche de techniques via le GraphQL azalee (`skills(q, limit)`). */
	remoteSearchWaza: (baseUrl: string, query: string) => typedError<unknown, string>(__TAURI_INVOKE("remote_search_waza", { baseUrl, query })),
	/**
	 *  Recherche plein-texte dans l'index CPK distant (250 800 fichiers, azalee) — utile en
	 *  complément du VFS local (comparaison, ou navigation sans avoir le jeu monté).
	 */
	remoteCpkSearch: (baseUrl: string, query: string) => typedError<unknown, string>(__TAURI_INVOKE("remote_cpk_search", { baseUrl, query })),
	/**
	 *  Résout les IDs de roster d'une sauvegarde (hash `0x........`) en noms réels via le miroir
	 *  serveur azalee — AUCUN octet de save ne transite, seulement les IDs déjà extraits en local
	 *  par `nie-save`. Anti-hallucination côté serveur : un ID absent revient `name: null`.
	 */
	remoteResolveRoster: (baseUrl: string, ids: string[]) => typedError<unknown, string>(__TAURI_INVOKE("remote_resolve_roster", { baseUrl, ids })),
	/**
	 *  Déchiffre + parse un fichier de sauvegarde Lives (ex. `002AB8F4-USERDATALIVE`) et renvoie
	 *  son résumé (`nie_save::SaveSummary`, sérialisé tel quel — joueur, niveau, temps de jeu,
	 *  roster…). Le conteneur déchiffré reste en mémoire pour [`save_list_blobs`]/[`save_export`].
	 */
	/**
	 *  Auto-détecte LA meilleure sauvegarde Steam Cloud (`userdata/<steamid>/2799860/remote/*-
	 *  USERDATALIVE`, cf. `steam::pick_best_save`) — `null` si Steam/le jeu/toute sauvegarde
	 *  valide est absent de ce poste (jamais un chemin deviné).
	 */
	defaultSavePath: () => __TAURI_INVOKE<string | null>("default_save_path"),
	saveOpen: (path: string) => typedError<unknown, string>(__TAURI_INVOKE("save_open", { path })),
	saveListBlobs: () => typedError<SaveBlobDto[], string>(__TAURI_INVOKE("save_list_blobs")),
	saveBlobHexB64: (index: number) => typedError<string, string>(__TAURI_INVOKE("save_blob_hex_b64", { index })),
	/**
	 *  Ré-encode le conteneur actuellement ouvert (round-trip octet-identique si rien n'a été
	 *  modifié) et l'écrit à `dest` — jamais l'original en place (choisi par l'utilisatrice).
	 */
	saveExport: (dest: string) => typedError<number, string>(__TAURI_INVOKE("save_export", { dest })),
	/**
	 *  Remuxe le flux vidéo H.264 d'un `.usm` en MP4 lisible par un `<video>` HTML (base64, borné).
	 *  VP9 brut n'est pas remuxable simplement (pas de conteneur) : renvoie une erreur claire.
	 */
	vfsVideoPreviewB64: (path: string, gameDir: string | null) => typedError<string, string>(__TAURI_INVOKE("vfs_video_preview_b64", { path, gameDir })),
	/** Même remuxage vidéo, depuis une entrée du CPK brut ouvert (hors VFS) — parité `RawCpkView`. */
	rawCpkVideoPreviewB64: (index: number) => typedError<string, string>(__TAURI_INVOKE("raw_cpk_video_preview_b64", { index })),
	/**
	 *  Assemble un G4MD+G4MG (+ G4TX frère si présent) en GLB autonome (textures embarquées) et le
	 *  rend via `nie-render3d` (rasterizer CPU pur-Rust, orbit-camera) → PNG (base64).
	 */
	vfsGlbPreviewPngB64: (path: string, gameDir: string | null) => typedError<string, string>(__TAURI_INVOKE("vfs_glb_preview_png_b64", { path, gameDir })),
	/**
	 *  Aperçu 3D **interactif** (§2.3 roadmap, « caméra orbitale ») : un turntable (36 images sur
	 *  360°) remuxé en MP4 par `nie-render3d`, affiché dans un `<video controls>` — la barre de
	 *  défilement native EST la caméra orbitale (glisser = tourner autour du modèle).
	 */
	vfsGlbPreviewTurntableMp4B64: (path: string, gameDir: string | null) =>
		typedError<string, string>(__TAURI_INVOKE("vfs_glb_preview_turntable_mp4_b64", { path, gameDir })),
	/**
	 *  Décode n'importe quel format audio Criware du VFS (`.acb`/`.awb`/`.hca`/`.adx`, dispatch par
	 *  magic) en WAV PCM16, base64 — `nie_formats::cri_audio::decode_to_wav` (feature `audio-decode`,
	 *  `cridecoder` + `IEVR_HCA_KEY` reversé de `nie.exe`, vérifié byte-exact sur `c00001001.awb`
	 *  (48 kHz mono, non silencieux) — cf. `docs/INVENTAIRE.md` § C1).
	 * 
	 *  Décodage lancé sur un THREAD DÉDIÉ à pile de 16 Mio : trouvé par test réel (pas supposé) —
	 *  `cridecoder` fait un vrai `STATUS_STACK_OVERFLOW` sur la pile debug par défaut (~1 Mio
	 *  Windows) sur `c01000010.awb` réel (fonctionne en `--release`, casse en `cargo build`/
	 *  `tauri dev`, le mode utilisé pendant tout le développement de cette app). Un
	 *  `STATUS_STACK_OVERFLOW` tue le PROCESS entier (fault SEH, pas rattrapable par
	 *  `catch_unwind`/`thread::join`) : la pile élargie doit réellement suffire, ce n'est pas un
	 *  filet de sécurité — reconfirmé : le même fichier décode sans erreur sur un thread à 16 Mio,
	 *  y compris en debug non optimisé.
	 */
	vfsAudioPreviewB64: (path: string, gameDir: string | null) => typedError<string, string>(__TAURI_INVOKE("vfs_audio_preview_b64", { path, gameDir })),
	/** Même décodage audio (HCA/ADX→WAV), depuis une entrée du CPK brut ouvert (hors VFS) — parité `RawCpkView`. */
	rawCpkAudioPreviewB64: (index: number) => typedError<string, string>(__TAURI_INVOKE("raw_cpk_audio_preview_b64", { index })),
	/** Aperçu 3D fixe (G4MD+G4MG+G4TX frères résolus DANS le CPK ouvert), depuis une entrée du CPK brut ouvert (hors VFS) — parité `RawCpkView` (roadmap §6, fermé 2026-08-08). */
	rawCpkGlbPreviewPngB64: (index: number) => typedError<string, string>(__TAURI_INVOKE("raw_cpk_glb_preview_png_b64", { index })),
	/** Pose une VRAIE liste de fichiers sur le presse-papiers Windows (CF_HDROP) — collable comme fichiers dans l'Explorateur, pas juste du texte. Inspiré de cosmic-files (`clipboard.rs`). */
	clipboardWriteFileList: (paths: string[]) => typedError<null, string>(__TAURI_INVOKE("clipboard_write_file_list", { paths })),
	/** Lit une VRAIE liste de fichiers depuis le presse-papiers Windows (CF_HDROP), `null` si absent (juste du texte, ou vide). */
	clipboardReadFileList: () => __TAURI_INVOKE<string[] | null>("clipboard_read_file_list"),
	/** Envoie des fichiers de l'espace de travail des mods (chemins relatifs à AppData) à la VRAIE Corbeille Windows — pas une suppression permanente. Inspiré de cosmic-files (`trash.rs`). */
	trashAppdataFiles: (appdataRelPaths: string[]) => typedError<null, string>(__TAURI_INVOKE("trash_appdata_files", { appdataRelPaths })),
	/** Installe/active l'extension Blender `niers` pour de vrai (dossier d'addons utilisateur, pas le bootstrap transitoire d'`openInBlender`) et lie `raw_data_root` au vrai `<jeu>/data`, persisté (`save_userpref`). */
	installNiersBlenderAddon: (blenderExe: string | null, gameDir: string | null) =>
		typedError<string, string>(__TAURI_INVOKE("install_niers_blender_addon", { blenderExe, gameDir })),
	/**  Ouvre N'IMPORTE QUEL `.blend` local en headless, cadre une caméra et rend un aperçu PNG base64. */
	blenderPreviewPngB64: (path: string, blenderExe: string | null) =>
		typedError<string, string>(__TAURI_INVOKE("blender_preview_png_b64", { path, blenderExe })),
	/**  Ouvre un `.blend` dans le vrai Blender GUI (process séparé, non bloquant). */
	blenderOpenScene: (path: string, blenderExe: string | null) =>
		typedError<null, string>(__TAURI_INVOKE("blender_open_scene", { path, blenderExe })),
	/**  Construit une scène Blender réelle : personnage (`internalCode`) + cut-in de technique (`skillQuery`). */
	blenderBuildSkillScene: (internalCode: string, skillQuery: string, blenderExe: string | null, gameDir: string | null) =>
		typedError<BlenderSceneResultDto, string>(
			__TAURI_INVOKE("blender_build_skill_scene", { internalCode, skillQuery, blenderExe, gameDir })
		),
};

/* Types */
export type EntryDto = {
	path: string,
	name: string,
	size: number,
	cpk: string,
};

export type FolderRoleDto = {
	role: string,
	status: string,
};

export type LsDto = {
	dirs: string[],
	files: EntryDto[],
	/**
	 *  Rôle du dossier courant (cf. `nie_explore::folder_roles`), `None` si non catalogué —
	 *  jamais un rôle deviné : la table ne couvre que ce qui est sourcé/vérifié.
	 */
	role: FolderRoleDto | null,
};

/**
 *  Une entrée à empaqueter dans un `.cpk` exporté (§1.2 roadmap) — `vfs_path` sert à dériver
 *  `directory`/`filename`, `staged_appdata_rel` est le chemin RELATIF sous `AppData` du fichier
 *  de remplacement déjà mis en scène dans le mod.
 */
export type CpkExportFileDto = {
	vfs_path: string,
	staged_appdata_rel: string,
};

export type PackFileDto = {
	/**
	 *  Chemin absolu réel sur disque (PAS un chemin interne VFS) — passé tel quel à
	 *  [`open_raw_cpk`] pour l'ouvrir.
	 */
	path: string,
	name: string,
	size: number,
};

export type RawCpkEntryDto = {
	/**
	 *  Index dans `CpkReader::entries` — clé stable pour les commandes suivantes (PAS le chemin :
	 *  deux entrées de dossiers différents peuvent partager un nom de fichier).
	 */
	index: number,
	path: string,
	size: number,
	is_compressed: boolean,
};

export type SaveBlobDto = {
	filename: string,
	subtype: string,
	size: number,
};

/**
 *  Technique (hissatsu) — port applati de `nie_data::skill::SkillInfo` + son texte joint
 *  (`skillNameId`/`skillDescId` résolus via `skill_text.cfg.bin`), pour l'IPC/l'export TS.
 */
export type SkillDto = {
	skill_id: string,
	skill_id_str: string,
	name: string | null,
	description: string | null,
	element: string,
	category: string,
	power_min: number,
	power_max: number,
	consume_tp: number,
	recast_time: number,
	eldorado: boolean,
};

/**
 *  Objet (arme/consommable/costume/…) — port applati de `nie_data::item::ItemInfo` + son texte
 *  joint (`item_text.cfg.bin`, mêmes noms ET descriptions), pour l'IPC/l'export TS. N'inclut que
 *  les objets à nom résolu (comme `nie-game/examples/export_items.rs`, roster réel).
 */
export type ItemDto = {
	item_id: string,
	category: string,
	name: string,
	description: string | null,
	price: number | null,
	internal_code: string | null,
};

/**
 *  Avatar/Keshin (aura) — port applati de `nie_data::aura::AuraCmd` + son texte joint
 *  (`skill_text.cfg.bin`, même table que les techniques). Le contenu signature d'IEVR.
 */
export type AuraDto = {
	aura_id: string,
	asset_code: string,
	name: string,
	description: string | null,
	element: string,
	sub_type: string,
};

/**
 *  Succès (trophy) — port applati de `nie_data::trophy::TrophyInfo` + son texte joint
 *  (`trophy_text.cfg.bin`) + condition de déblocage décodée (`decode_unlock`).
 */
export type TrophyDto = {
	trophy_id: string,
	code: string,
	category: number,
	name: string,
	description: string | null,
	unlock_kind: string,
	story_episode: number | null,
};

/**
 *  Quête — port applati de `nie_data::quest::ParsedQuest` + son titre joint
 *  (`quest_title_text.cfg.bin`). N'inclut que les quêtes à titre résolu (roster réel).
 */
export type QuestDto = {
	quest_id: string,
	phase: number,
	quest_type: number,
	title: string,
	image: string | null,
};

/**
 *  Personnage sélectionnable pour le calculateur de stats (§4.2 roadmap) — `nie_data::chara_param
 *  ::CharaParam` joint à `chara_base`/`chara_text` pour un nom affichable. N'inclut que les
 *  entrées à nom résolu (roster réel, même convention que les autres `list_*`).
 */
export type CharaPickerDto = {
	chara_param_id: string,
	name: string,
	main_position: string,
	sub_position: string,
};

/** Bloc de 7 stats calculées (`nie_core::stats::StatBlock`), pour l'IPC/l'export TS. */
export type StatBlockDto = {
	kc: number,
	cr: number,
	tc: number,
	pr: number,
	ps: number,
	ag: number,
	it: number,
	total: number,
};

export type StatsDto = {
	total: number,
	cpk_count: number,
	extra_count: number,
	loose_count: number,
	top_ext: ([string, number])[],
};

export type BlenderSceneResultDto = {
	blend_path: string,
	preview_png_b64: string | null,
	skill_name: string,
	event_id_name: string,
	warnings: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

